# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://xuhaoblog.com
baseurl: /
title: Xu Hao's Site
description: >
    主要用于分享日常学习、生活及工作的一些心得总结


## => Language and Timezone
##############################
lang: zh
timezone: Asia/Hangzhou


## => Author and Social
##############################
author:
  name: 徐昊 Xiho
  email: igeekho@gmail.com
  github:  git-xuhao
  weibo: xuxiho
  facebook: google.xu



## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: git-xuhao/gi-xuhao.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
license: CC-BY-4.0


## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: disqus
  disqus:
    shortname: kitian616-github-io


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
    app_key: Mzf5m9skSwYVWVXhGiYMNyXs
    app_class: ThomasBlog


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id: UA-71907556-1


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001