# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://xuhaoblog.com
baseurl: /
title: Xu Hao's Site
description: >
    主要用于分享日常学习、生活及工作的一些心得总结


## => Language and Timezone
##############################
lang: zh
timezone: Asia/Hangzhou


## => Author and Social
##############################
author:
  name: 徐昊 Xiho
  email: igeekho@gmail.com
  github:  git-xuhao
  weibo: xuxiho
  facebook: google.xu



## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: git-xuhao/gi-xuhao.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
license: CC-BY-4.0


## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: gitalk
  gitalk:
    clientID    : 3d507f3b58e98bd4c002
    clientSecret: 20eb5562ff08dcc12a9a61edbdb8b29f9135e302
    repository  : "git-xuhao.github.io"
    owner       : "git-xuhao"
    admin: # Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
      - "git-xuhao"


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: db0QWTbzNHkUbR4g6lK859ao-gzGzoHsz
    app_key: 1JNOBbvRKLuklIw1CXsSvJp4
    app_class: BlogCounter


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id: UA-122974929-1


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  
# Mathjax
mathjax: true
mathjax_autoNumber: true

# Mermaid
mermaid: true

# Chart
chart: true

## => Server
##############################
server_url: "0.0.0.0"
port: 4001